name: Add Compatibility Label to Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main  # Adjust if your default branch is different

jobs:
  add_compatibility_label:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Analyze PR for Compatibility
        id: compatibility
        run: |
          # Placeholder for actual compatibility analysis
          # For demonstration, we'll set a fixed compatibility score
          COMPATIBILITY_SCORE=100
          echo "score=$COMPATIBILITY_SCORE" >> $GITHUB_OUTPUT

      - name: Add Compatibility Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "compatibility: ${{ steps.compatibility.outputs.score }}%"
