name: Build and Push DockerSnap Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: false
        default: main
      testing:
        description: Testing workflow
        required: false
        type: boolean
        default: false
  push:
    branches: 
      - main
    paths:
      - 'DockerSnap.sh'
      - 'Dockerfile'

jobs:
  build-and-push:
    env:
      DOCKER_REGISTRY: docker.io
      DS_GITHUB_REGISTRY: ghcr.io
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up QEMU and Docker Buildx (for multi-platform builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Step 3: Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true   # Retry even if login fails

      # Step 4: Login to GitHub Container Registry
      - name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DS_GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true   # Retry even if login fails

      # Step 5: Build DockerSnap Image for multiple platforms (e.g., linux/amd64, linux/arm64)
      - name: Build DockerSnap Image
        run: |
          docker buildx create --use
          docker buildx build . --platform linux/amd64,linux/arm64 \
            -t ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USER }}/dockersnap:latest \
            -t ${{ env.DS_GITHUB_REGISTRY }}/${{ github.repository_owner }}dockersnap:latest \
            --push   # Push the image directly after build to avoid separate push step

      # Step 6: Add summary details
      - name: Add Summary Details
        if: always()
        run: |
          echo "## Summary Details" >> $GITHUB_STEP_SUMMARY
          echo "* Docker Image (Docker Hub): [${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USER }}/dockersnap:latest](https://${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USER }}/dockersnap)" >> $GITHUB_STEP_SUMMARY
          echo "* Docker Image (GitHub): [${{ env.DS_GITHUB_REGISTRY }}/${{ github.repository_owner }}/dockersnap:latest](https://${{ env.DS_GITHUB_REGISTRY }}/${{ github.repository_owner }}/dockersnap)" >> $GITHUB_STEP_SUMMARY
          echo "* Branch: ${{ github.event.inputs.branch }}" >> $GITHUB_STEP_SUMMARY
          echo "* Testing: ${{ github.event.inputs.testing }}" >> $GITHUB_STEP_SUMMARY

      # Step 7: Cleanup Docker Images
      - name: Cleanup Docker Images
        run: |
          docker image prune -a --force
